/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.rit.cs.dbc.view;

import edu.rit.cs.dbc.controller.MovieTableController;

/**
 * The main application screen for holding screens and tables 
 * about movie data
 */
public class DatabaseMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseMainFrame
     */
    public DatabaseMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPane = new javax.swing.JTabbedPane();
        browseMoviesPanel = new edu.rit.cs.dbc.view.BrowseMoviesPanel();
        browseMoviesPanel.registerController(movieTableController);
        memberQueuePanel = new edu.rit.cs.dbc.view.MemberQueuePanel();
        memberQueuePanel.registerController(movieTableController);
        purchasePanel = new edu.rit.cs.dbc.view.PurchasePanel();
        recentPanel = new edu.rit.cs.dbc.view.RecentPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabPane.setPreferredSize(new java.awt.Dimension(500, 600));
        TabPane.addTab("Browse", browseMoviesPanel);
        TabPane.addTab("Queue", memberQueuePanel);

        purchasePanel.registerController(movieTableController);
        TabPane.addTab("Purchases", purchasePanel);

        recentPanel.registerController(movieTableController);
        TabPane.addTab("Recent", recentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPane;
    private edu.rit.cs.dbc.view.BrowseMoviesPanel browseMoviesPanel;
    private edu.rit.cs.dbc.view.MemberQueuePanel memberQueuePanel;
    private edu.rit.cs.dbc.view.PurchasePanel purchasePanel;
    private edu.rit.cs.dbc.view.RecentPanel recentPanel;
    // End of variables declaration//GEN-END:variables

    // the mediator for passing to the views contained within this main frame
    private MovieTableController movieTableController = new MovieTableController();

}
