/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.rit.cs.dbc.view;

import edu.rit.cs.dbc.controller.MovieTableController;

/**
 *
 * @author ptr5201
 */
public class MemberQueuePanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberQueuePanel
     */
    public MemberQueuePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        moviesQueueScrollPane = new javax.swing.JScrollPane();
        moviesQueueTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        purchaseButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(495, 561));
        setLayout(new java.awt.BorderLayout());

        MovieTableController movieTableController = new MovieTableController(queueMoviesTableModel);
        movieTableController.loadQueueMoviesTable();
        moviesQueueTable.setModel(queueMoviesTableModel);
        moviesQueueTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        moviesQueueScrollPane.setViewportView(moviesQueueTable);

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moviesQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moviesQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(upperPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setPreferredSize(new java.awt.Dimension(400, 58));

        purchaseButton.setText("Purchase");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchaseButton)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchaseButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane moviesQueueScrollPane;
    private javax.swing.JTable moviesQueueTable;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

    private MoviesTableModel queueMoviesTableModel = new MoviesTableModel();
}
