/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.rit.cs.dbc.view;

import edu.rit.cs.dbc.DatabaseApp;
import edu.rit.cs.dbc.db.DatabaseConnection;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author owen
 */
public class NewUserCreationFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewUserCreationFrame
     */
    public NewUserCreationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userFormPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        verifyPasswordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        verifyPasswordTextField = new javax.swing.JPasswordField();
        fullNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        errorAndButtonPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        errorLabel.setVisible(false);
        closeButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New User");

        usernameLabel.setText("Username:");

        fullNameLabel.setText("Full Name:");

        passwordLabel.setText("Password:");

        verifyPasswordLabel.setText("Verify Password:");

        org.jdesktop.layout.GroupLayout userFormPanelLayout = new org.jdesktop.layout.GroupLayout(userFormPanel);
        userFormPanel.setLayout(userFormPanelLayout);
        userFormPanelLayout.setHorizontalGroup(
            userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(userFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(userFormPanelLayout.createSequentialGroup()
                        .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(fullNameLabel)
                            .add(usernameLabel))
                        .add(52, 52, 52)
                        .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(fullNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .add(usernameTextField)))
                    .add(userFormPanelLayout.createSequentialGroup()
                        .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(passwordLabel)
                            .add(verifyPasswordLabel))
                        .add(18, 18, 18)
                        .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(passwordTextField)
                            .add(verifyPasswordTextField))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userFormPanelLayout.setVerticalGroup(
            userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(userFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameLabel)
                    .add(usernameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fullNameLabel)
                    .add(fullNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(passwordLabel)
                    .add(passwordTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(userFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(verifyPasswordLabel)
                    .add(verifyPasswordTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usernameTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );
        verifyPasswordTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );
        fullNameTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );
        passwordTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Error Label");
        errorLabel.setName(""); // NOI18N

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout errorAndButtonPanelLayout = new org.jdesktop.layout.GroupLayout(errorAndButtonPanel);
        errorAndButtonPanel.setLayout(errorAndButtonPanelLayout);
        errorAndButtonPanelLayout.setHorizontalGroup(
            errorAndButtonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(errorAndButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(errorAndButtonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(errorLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(errorAndButtonPanelLayout.createSequentialGroup()
                        .add(closeButton)
                        .add(18, 18, 18)
                        .add(createAccountButton)
                        .add(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        errorAndButtonPanelLayout.setVerticalGroup(
            errorAndButtonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(errorAndButtonPanelLayout.createSequentialGroup()
                .add(errorLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(errorAndButtonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(closeButton)
                    .add(createAccountButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(errorAndButtonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(userFormPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(userFormPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(errorAndButtonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        if (!"".equals(usernameTextField.getText()) &&
                !"".equals(fullNameTextField.getText()) && 
                !"".equals(new String(passwordTextField.getPassword())) &&
                !"".equals(new String(verifyPasswordTextField.getPassword()))) {
            
            if (new String(passwordTextField.getPassword()).equals(new String(verifyPasswordTextField.getPassword()))) {
                if (!DatabaseConnection.getInstance().memberExists(usernameTextField.getText())) {
                    if (DatabaseConnection.getInstance().createMember(
                        usernameTextField.getText(), fullNameTextField.getText(), new String(passwordTextField.getPassword()))) {
                        dispose();
                        DatabaseApp.displayLogin();
                    }
                } else {
                    setErrorLabel(true, "Username exists");
                }
            } else {
                setErrorLabel(true, "Passwords don't match");
            }
        } else {
            setErrorLabel(true, "One or more empty fields");
        }
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // Close
        dispose();
        DatabaseApp.displayLogin();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void setErrorLabel(boolean visible, String errorMessage) {
        if (errorLabel.isVisible() != visible) {
            errorLabel.setVisible(visible);
        }
        errorLabel.setText(errorMessage);
        pack();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JPanel errorAndButtonPanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel userFormPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel verifyPasswordLabel;
    private javax.swing.JPasswordField verifyPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
