/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.rit.cs.dbc.view;

import edu.rit.cs.dbc.db.DatabaseConnection;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * A user form for registering new members into the system
 */
public class NewUserCreationFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewUserCreationFrame
     */
    public NewUserCreationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userFormPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        verifyPasswordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        verifyPasswordTextField = new javax.swing.JPasswordField();
        fullNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        errorAndButtonPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        errorLabel.setVisible(false);
        closeButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New User");

        usernameLabel.setText("Username:");

        fullNameLabel.setText("Full Name:");

        passwordLabel.setText("Password:");

        verifyPasswordLabel.setText("Verify Password:");

        javax.swing.GroupLayout userFormPanelLayout = new javax.swing.GroupLayout(userFormPanel);
        userFormPanel.setLayout(userFormPanelLayout);
        userFormPanelLayout.setHorizontalGroup(
            userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userFormPanelLayout.createSequentialGroup()
                        .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullNameLabel)
                            .addComponent(usernameLabel))
                        .addGap(52, 52, 52)
                        .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fullNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(usernameTextField)))
                    .addGroup(userFormPanelLayout.createSequentialGroup()
                        .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(verifyPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(verifyPasswordTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userFormPanelLayout.setVerticalGroup(
            userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameLabel)
                    .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyPasswordLabel)
                    .addComponent(verifyPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usernameTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );
        verifyPasswordTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );
        fullNameTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );
        passwordTextField.getDocument().addDocumentListener(
            new DocumentListener() {
                public void changedUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void insertUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
                public void removeUpdate(DocumentEvent e) {
                    setErrorLabel(false, "");
                }
            }
        );

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Error Label");
        errorLabel.setName(""); // NOI18N

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorAndButtonPanelLayout = new javax.swing.GroupLayout(errorAndButtonPanel);
        errorAndButtonPanel.setLayout(errorAndButtonPanelLayout);
        errorAndButtonPanelLayout.setHorizontalGroup(
            errorAndButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorAndButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorAndButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(errorAndButtonPanelLayout.createSequentialGroup()
                        .addComponent(closeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(createAccountButton)))
                .addContainerGap())
        );
        errorAndButtonPanelLayout.setVerticalGroup(
            errorAndButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorAndButtonPanelLayout.createSequentialGroup()
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(errorAndButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(createAccountButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorAndButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorAndButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Attempts to submit a request to create a new user with the 
     * specified credentials
     * @param evt the action event triggered by the "Create Account" button
     */
    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        // only proceed if none of the fields are empty; otherwise, display
        // an error message that none of the fields can be empty
        // in an error label
        if (!"".equals(usernameTextField.getText()) &&
                !"".equals(fullNameTextField.getText()) && 
                !"".equals(new String(passwordTextField.getPassword())) &&
                !"".equals(new String(verifyPasswordTextField.getPassword()))) {
            
            // if the passwords in both fields match, then proceed; 
            // otherwise, display an error message that the passwords
            // don't in an error label
            if (new String(passwordTextField.getPassword()).equals(new String(verifyPasswordTextField.getPassword()))) {
                // attempt to create a user only if the user does
                // not yet exist; otherwise, display an error message
                // that the username is already taken
                if (!DatabaseConnection.getInstance().memberExists(usernameTextField.getText())) {
                    if (DatabaseConnection.getInstance().createMember(
                        usernameTextField.getText(), fullNameTextField.getText(), new String(passwordTextField.getPassword()))) {
                        dispose();
                        new LoginScreen().setVisible(true);
                    }
                } else {
                    setErrorLabel(true, "Username exists");
                }
            } else {
                setErrorLabel(true, "Passwords don't match");
            }
        } else {
            setErrorLabel(true, "One or more empty fields");
        }
    }//GEN-LAST:event_createAccountButtonActionPerformed

    /**
     * Closes the registration form and returns back to the login screen
     * @param evt the action event triggered by the "Close" button
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // Close
        dispose();
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * Sets the visibility and error message of the error label
     * @param visible true if the error label should be displayed;
     *                false if otherwise
     * @param errorMessage the message of the error to be displayed
     */
    private void setErrorLabel(boolean visible, String errorMessage) {
        if (errorLabel.isVisible() != visible) {
            errorLabel.setVisible(visible);
        }
        errorLabel.setText(errorMessage);
        pack();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JPanel errorAndButtonPanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel userFormPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel verifyPasswordLabel;
    private javax.swing.JPasswordField verifyPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
