/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.rit.cs.dbc.view;

import edu.rit.cs.dbc.controller.MovieTableController;
import edu.rit.cs.dbc.model.Movie;
import edu.rit.cs.dbc.model.MovieTableModel;
import edu.rit.cs.dbc.model.Purchase;
import edu.rit.cs.dbc.model.PurchaseMovieTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author owen
 */
public class PurchasePanel extends javax.swing.JPanel {

    /**
     * Creates new form PurchasePanel
     */
    public PurchasePanel() {
        initComponents();
    }
    public void registerController(MovieTableController movieTableController) {
        this.movieTableController = movieTableController;
        this.movieTableController.registerPurchasedPanel(this);
        this.movieTableController.loadPurchasedMoviesTable();
    }

    public PurchaseMovieTableModel getPurchaseMovieTableModel() {
        return purchaseMovieTableModel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        watchButton = new javax.swing.JButton();
        statButton = new javax.swing.JButton();
        upperPanel = new javax.swing.JPanel();
        purchaseScrollPane = new javax.swing.JScrollPane();
        purchaseTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        buttonPanel.setPreferredSize(new java.awt.Dimension(400, 58));

        watchButton.setText("Watch");
        watchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchButtonActionPerformed(evt);
            }
        });

        statButton.setText("My Statistics");
        statButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(watchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(statButton)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(watchButton)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statButton)
                .addContainerGap())
        );

        add(buttonPanel, java.awt.BorderLayout.SOUTH);

        purchaseTable.setModel(purchaseMovieTableModel);
        purchaseTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        purchaseScrollPane.setViewportView(purchaseTable);

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchaseScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchaseScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(upperPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void watchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchButtonActionPerformed
        int selectedRow = purchaseTable.getSelectedRow();
        if (selectedRow > -1) {
            selectedRow = purchaseTable.convertRowIndexToModel(selectedRow);
            Purchase p = purchaseMovieTableModel.getPurchaseAt(selectedRow);
            movieTableController.watchMovie(p.getMovie());
        }
    }//GEN-LAST:event_watchButtonActionPerformed

    private void statButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButtonActionPerformed
        
        JOptionPane.showMessageDialog(this, "Dialog", "User Statistics", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_statButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane purchaseScrollPane;
    private javax.swing.JTable purchaseTable;
    private javax.swing.JButton statButton;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JButton watchButton;
    // End of variables declaration//GEN-END:variables
    
    private PurchaseMovieTableModel purchaseMovieTableModel = new PurchaseMovieTableModel();
    private MovieTableController movieTableController;
}
